
def str():
	print "Option			Default Value 	Description"
	print "'calcs':		['Compute']	Internal flag. Can also include"
	print "					'Results' if analyzing output from MPEx"
	print "'fasta':		None		Name of fasta file. Not required if"
	print "					analyzing MPEx output."
	print "'MPEX_fil':		None		Name of MPEx file. Not required if"
	print "					analyzing fasta file."
	print "'MPEX_opts':		None		Currently not being used."
	print "'dG_scale':		'interface'	Hydropathy scales: interface, octanol,"
	print "					octanol-interface, kyte-doolittle, charge"
	print "'smooth_window':	False		Smooth the already smoothed curves"
	print "'standard_plot':	False		Plot either dG or autocorrelation(dG)"
	print "'auto':			False		Choose either dG or auto(dG)"
	print "'fit_to_sin':		False		Fit dG curve to sine wave"
	print "'display_sin':		False		Display curve fits (unaligned)"
	print "'plot_phi_shift':	False		Align fitted curves by phase shift (and plot)"
	print "'r_cutoff':		0.2		r^2 cutoff to accept fit"
	print "'use_weblogo':		False		Print a consensus sequence as x-axis of plot"
	print "'weblogo_txt':		''		Text"
	print "'add_peaks':		False		Use SciPy function to find peaks in autocorr plot"
	print "'auto_filter':		False		Filter out sequences with aperiodic dG curves"
	print "'ac_cutoff':		-0.3		Cutoff for auto_filter. Lower numbers = more periodic"
	print "'plot_auto_filter':	False		Show periodic sequences only"
	print "'is_reflectin':		False		Special case"
	print "'isref_analysis':	False		Special case"
	print "'make_palign':		False		Special case"
	print "'print_palign':		False		Special case"
	print "'ex_seq':		''		Special case"
	print "'print_fasta':		False		Special case. Print fasta containing sequences"
	return None
